public enum State {
    WELCOME,
    VIEW_TASK_1,
    SOLVED_TASK_1,
    VIEW_TASK_2,
    SOLVED_TASK_2,
    VIEW_TASK_3_1,
    SOLVED_TASK_3_1,
    VIEW_TASK_3_2,
    SOLVED_TASK_3_2,
    VIEW_TASK_4_1,
    SOLVED_TASK_4_1,
    VIEW_TASK_4_2,
    SOLVED_TASK_4_2
}
